backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/assets/images
public_folder: /assets/images
 

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", multiple: true }
  - name: "insights"
    label: "Insights"
    folder: "content/insights"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    editor: 
      preview: false
    fields:
      - { label: "Insights", name: "tags", widget: "list" }
      - { label: 'Ideas for later', name: 'image', widget: 'image', required: false, tagname: '' }
      - { label: "Description", name: "description", widget: "string" }
      - { label: 'Color', name: 'color', widget: 'color', enableAlpha: true, allowInput: true }
    
 

  
      